### ISSUE TITLE
Too many submissions cause rate limit error from Leetcode API: 403

### ISSUE THREAD

**Issue by dengl11** [joshcai/leetcode-sync#1]
I have lots of submissions on Leetcode; so the action fails after ~480 submission fetched from their API:

```
Getting submission from LeetCode, offset 0
Getting submission from LeetCode, offset 20
Getting submission from LeetCode, offset 40
Getting submission from LeetCode, offset 60
Getting submission from LeetCode, offset 80
Getting submission from LeetCode, offset 100
Getting submission from LeetCode, offset 120
Getting submission from LeetCode, offset 140
Getting submission from LeetCode, offset 160
Getting submission from LeetCode, offset 180
Getting submission from LeetCode, offset 200
Getting submission from LeetCode, offset 220
Getting submission from LeetCode, offset 240
Getting submission from LeetCode, offset 260
Getting submission from LeetCode, offset 280
Getting submission from LeetCode, offset 300
Getting submission from LeetCode, offset 320
Getting submission from LeetCode, offset 340
Getting submission from LeetCode, offset 360
Getting submission from LeetCode, offset 380
Getting submission from LeetCode, offset 400
Getting submission from LeetCode, offset 420
Getting submission from LeetCode, offset 440
Getting submission from LeetCode, offset 460
Getting submission from LeetCode, offset 480
##[error]Error: Request failed with status code 403
```

Can we have another argument in the action inputs to specify **maximum number of submissions we want to fetch for each action**?

Thanks!

**Comment by joshcai** [comment]
Thank you for the bug report, @dengl11! I have tried adding some retries with exponential backoff since it looks like a rate-limiting issue.

Do you mind trying at this version?: 43b4e9b, e.g. in the workflow yaml instead of:

      uses: joshcai/leetcode-sync@v1.0

use:

      uses: joshcai/leetcode-sync@43b4e9b

If it works, then I can create a new release with the bug fix.

**Comment by joshcai** [comment]
Let me know if it works with @v1.1 - I changed the rate limiting code based on trying a lot of requests in a row, thanks!

**Comment by dengl11** [comment]
Sorry Josh for the late reply! 

I retried a few weeks ago and yesterday; still failing. I am now looking into the error and trying to see if I can find something interesting there. Hopefully I can give an update here in a few days.

Thanks!

**Comment by dengl11** [comment]
Hi Josh, I just retried and it seems that it is almost working for me! 
```
Getting submission from LeetCode, offset 380
Getting submission from LeetCode, offset 400
Error fetching submissions, retrying in 1 seconds...
Error fetching submissions, retrying in 3 seconds...
Error fetching submissions, retrying in 9 seconds...
Error fetching submissions, retrying in 27 seconds...
Getting submission from LeetCode, offset 420
Syncing 737 submissions...
... lots of Committing solution for ...
##[error]HttpError: API rate limit exceeded for installation ID 10475424.
```
I can now see tons of my leetcode submissions now in my github: https://github.com/dengl11/Leetcode/tree/master/problems

This is super awesome!

I guess there might be two reasons that it was failing for me after you fixed the too many leetcode submission problems:

1. It has been a while since I last logged in to LeetCode; so I was getting 403 when running the action. I fixed it by having a fresh log in to LeetCode.
2. I did not use your most recent action. I fixed it by using your latest commit hash in my yml file:
```
uses: joshcai/leetcode-sync@99f3592
```

I suspect the final `HttpError: API rate limit exceeded for installation ID 10475424` might be one Github side. Let me take a further look.

**Comment by dengl11** [comment]
I opened a PR [here](https://github.com/joshcai/leetcode-sync/pull/3) and verified that it is fully working now:
![Screen Shot 2020-09-20 at 10 10 40 AM](https://user-images.githubusercontent.com/10295374/93717368-2ff4ec00-fb2a-11ea-8ae1-198eec893fbb.png)

**Comment by dengl11** [comment]
With the caveat that I did hit a "Request quota exhausted for request POST /repos/{owner}/{repo}/git/trees" error in the second last run (after I used the throttling plugin). I guess it means that the total number of request yesterday has exceeded the quota. Seems that there is no so much that we can do except
1) programmatically waiting until the next day (which does not make much sense for uses)
2) manually re-run the action the next day 

The last successful run is from 2).

**Comment by joshcai** [comment]
Thanks Tony for patiently retrying so many times! I'm glad the LeetCode rate limit is resolved now. 

I agree with option (2) from your last comment, since the action is written in a way to tolerate these kinds of failures by writing in reverse chronological order. I will update the documentation about this issue, thanks for discovering it! 

Will go ahead and close this particular issue since it seems the LeetCode part is working now.

**Comment by dengl11** [comment]
Thanks Josh!
