### ISSUE TITLE
 HttpError: At least 1 approving review is required by reviewers with write access.

### ISSUE THREAD

**Issue by Ahmad-Abdalmageed** [joshcai/leetcode-sync#19]
Need help with error 

![image](https://user-images.githubusercontent.com/43472368/179799045-2be5c587-6e6c-4f37-8016-3c5b7c461dc9.png)

`

    name: Sync Leetcode

    on:
      workflow_dispatch:
      schedule:
        - cron:  '0 8 * * 6'
    
    jobs:
      build:
        runs-on: ubuntu-latest

    steps:
    - name: Sync
      uses: joshcai/leetcode-sync@v1.4
      with:
        github-token: ${{ github.token }}
        leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
        leetcode-session: ${{ secrets.LEETCODE_SESSION }}
        destination-folder: LeetCodeSolutions`

**Comment by joshcai** [comment]
Hi @Ahmad-Abdalmageed, sorry for the delayed response. I'm assuming you have some kind of branch protection on your repo? https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches 

Is it possible to disable that for your repo? (if you're still having this issue)

**Comment by Ahmad-Abdalmageed** [comment]
I removed the Protection Yes, I don't have this problem anymore. Thank You
