### ISSUE TITLE
Invalid file path when problem title contains special character

### ISSUE THREAD

**Issue by hucancode** [joshcai/leetcode-sync#49]
There is a problem with special character in their title will result in invalid path
For example, this problem: [Is Graph Bipartite?](https://leetcode.com/problems/is-graph-bipartite/)
Will result in this path `leetcode/problems/is_graph_bipartite?/solution.rs` which contains invalid character `?` (at least it is invalid in Windows)

**Comment by joshcai** [comment]
Thanks for reporting @hucancode! Apologies for the delay on getting to this, but this should be fixed now.
