### ISSUE TITLE
Issue with Github token

### ISSUE THREAD

**Issue by mohitathwani** [joshcai/leetcode-sync#5]
My action fails and from the screenshot I see that it is able to connect to Leetcode, but it fails on the commit step, which probably means the GitHub token is not configured correctly?

![Screen Shot 2020-10-03 at 3 48 41 PM](https://user-images.githubusercontent.com/1278646/95003097-6d2c9580-0590-11eb-8ad7-ad2d41ca551b.png)

**Comment by joshcai** [comment]
Hi @mohitathwani, thanks for reporting this issue! I think this is due to the rename from "master" to "main" for the default branch by GitHub - I will work on a fix shortly. 

More Info: https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

**Comment by joshcai** [comment]
I pushed a new release that should contain the fix. Could you try it and let me know if it works for you? To use the new release, just use "joshcai/leetcode-sync@v1.2" in your action's .yml configuration file.

**Comment by mohitathwani** [comment]
Works like a charm! Thank you for this tool :)
