### ISSUE TITLE
Leetcode now has challenge page

### ISSUE THREAD

**Issue by kbiits** [joshcai/leetcode-sync#56]
Request to the leetcode API always return 403 status. 

Below is the sample response. I tried to bypass it by modifying and adding some http headers, but still got the 403 error. 
<img width="1027" alt="image" src="https://github.com/joshcai/leetcode-sync/assets/67781184/16e1267e-4eef-423f-a7cf-9b40458f6e3f">

**Comment by ckcherry23** [comment]
I am getting an error 403 since 2 days as well.

<img width="1112" alt="Screenshot 2024-03-10 at 11 47 30 AM" src="https://github.com/joshcai/leetcode-sync/assets/68203159/d182b109-d29e-4c8c-819f-7bed37b93c67">

**Comment by ali-john** [comment]
I am also having the same issue

**Comment by ajmedeio** [comment]
I as well.

**Comment by yehezkielgunawan** [comment]
I think I'm not alone. I also having the same issue

**Comment by ckcherry23** [comment]
Hi @joshcai, thanks for creating this action! Are there any plans to fix this issue?

**Comment by joshcai** [comment]
The commit I just added is working for my repository, could anyone else confirm that it's working for them (use @master in the .yml file)? I can make a new release with this code shortly after it's verified to be fixed.

**Comment by kbiits** [comment]
Did you modify any configurations @joshcai ? Because it's not working for me.

First, I got this error and it's solved by updating the CSRF and session token 
<img width="761" alt="image" src="https://github.com/joshcai/leetcode-sync/assets/67781184/c5c9d02c-424a-4db8-996e-eaa4396324ee">

After I updated the csrf and session token, I got another error here.
<img width="806" alt="image" src="https://github.com/joshcai/leetcode-sync/assets/67781184/e03d9faf-1865-4224-9141-2d49d7e8de20">

**Comment by joshcai** [comment]
Thanks for trying @kbiits! I can't reproduce this error on my repo, but I recall seeing that issue in https://github.com/joshcai/leetcode-sync/issues/22, do you have `destination-folder` set? I think I can also just strip the trailing `/` if that's the issue for you as well.

**Comment by kbiits** [comment]
I don't have `destination-folder` set. Let me try to debug it and will get back to you with the details of question and solution path

**Comment by kbiits** [comment]
@joshcai I also didn't see anything wrong about the paths here
<img width="758" alt="image" src="https://github.com/joshcai/leetcode-sync/assets/67781184/a5d7e51e-cd7c-4d67-a94f-c3eea95dc9fd">

Fyi, the error is thrown when caling `octokit.git.createTree`, not the `octokit.git.createCommit`

**Comment by joshcai** [comment]
@kbiits Ah I looked into it more, and the default for the destination folder changing to "." caused the issue. I have now normalized the path so it shouldn't be an issue anymore.

@siriscmv thanks for reporting! I only tested on a single batch, the has_next feature was affected by the graphql changes. I plan on adding some unit tests to help with testing in the future. 

I think all issues should be fixed now with the latest commit.

**Comment by joshcai** [comment]
I released a new version `v1.6` that should work, please feel free to re-open if anything is broken - closing this for now.

**Comment by kbiits** [comment]
Thanks. It works well now @joshcai

**Comment by Gurubalan-GIT** [comment]
Thanks for getting on this, appreciate this a lot! - @joshcai
