### ISSUE TITLE
TypeError: response.data.data.submissionList.submissions is not iterable

### ISSUE THREAD

**Issue by 10622130** [joshcai/leetcode-sync#60]
I followed the README.md guide and got this error "TypeError: response.data.data.submissionList.submissions is not iterable", I'm using the latest version of joshcai/leetcode-sync@v1.6.

here is my .yml:
name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: LeetCode Sync
        uses: joshcai/leetcode-sync@v1.6
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.csrftoken }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-folder
          verbose: true
          commit-header: '[LeetCode Sync]'

**Comment by samgabel** [comment]
@10622130 make sure you are setting your `LEETCODE_CSRF_TOKEN` & `LEETCODE_SESSION` correctly in your github repo secrets. I typically see the error message you described when I either enter in the secrets incorrectly, or enough time has passed where I need to update to a new cookie.

**Comment by 10622130** [comment]
@samgabel  Do I have to replace the ; and the end of ``LEETCODE_CSRF_TOKEN` & `LEETCODE_SESSION` ` with " " ? Because I'm pretty sure I have the right token.

**Comment by samgabel** [comment]
@10622130 I have not tried it with the semicolon included. I usually enter it in without the semicolon. `LEETCODE_CSRF_TOKEN`=zzzzz

**Comment by 10622130** [comment]
it worked, thanks

**Comment by thomHayner** [comment]
My CSRF Token remained the same but I had to update the LEETCODE_SESSION cookie.

Seems annoying to have to update this constantly.
Is anyone aware of a workaround or know of a way to automate this?
