### ISSUE TITLE
No Longer Have LC Premium - Issue Committing Locked Problems

### ISSUE THREAD

**Issue by Ishxnnn** [joshcai/leetcode-sync#61]
Context: I bought one month of LC premium for an interview a few months ago. Cancelled the premium subscription after the interview, but I did a few locked problems during that time. I no longer have LC premium but I still LeetCode regularly. My tasks were failing and I finally got the chance to look into why:

![image](https://github.com/joshcai/leetcode-sync/assets/89994410/b387c61e-caa2-4ab3-91f9-4a67eedfd77f)

It seems the HTTP request to the locked "Meeting Rooms" problem is failing because the problem is now locked for me even though I've already solved it (I think this is why my LC count on my profile went down as well lol).

Any way to kind of "skip" locked problems in this case so that other problems can get synced? I am assuming there's no way to get locked problem solutions in my case unless I rebuy LC premium.

**Comment by joshcai** [comment]
Hi @Ishxnnn, thanks for finding this issue. I suspect https://github.com/joshcai/leetcode-sync/pull/62 should fix this issue when merged.

**Comment by joshcai** [comment]
This should be released in v1.7, please re-open if it is still causing issues - thanks!
