### ISSUE TITLE
csrf expired, Error: Request failed with status code 401

### ISSUE THREAD

**Issue by shengchen-liu** [joshcai/leetcode-sync#7]
`Error: Request failed with status code 401`
This error happens every few days.  Every time this error happens I need to login to Leetcode and manually fetch the latest csrf token and update `LEETCODE_CSRF_TOKEN`.

Is there any other way to automatically update this token?

**Comment by joshcai** [comment]
Thanks for reporting this @shengchen-liu. I also noticed my runs failing recently for the same reason, seems like it may be a change in LeetCode's behavior (previously my action had been working for months without needing to update the tokens).

I plan to work on a Chrome extension (which will be able to have access to the relevant cookies) so that the values can be automatically updated, I will update this issue when it is ready. Sorry for the inconvenience in the meanwhile.

**Comment by shengchen-liu** [comment]
Thank you for the quick response.  Thank you for your effort!

**Comment by shengchen-liu** [comment]
> 
> 
> Thanks for reporting this @shengchen-liu. I also noticed my runs failing recently for the same reason, seems like it may be a change in LeetCode's behavior (previously my action had been working for months without needing to update the tokens).
> 
> I plan to work on a Chrome extension (which will be able to have access to the relevant cookies) so that the values can be automatically updated, I will update this issue when it is ready. Sorry for the inconvenience in the meanwhile.

Thank you for the quick response. Thank you for your effort!

**Comment by shengchen-liu** [comment]
I found a similar chrome extension [here ](https://docs.rs/leetcode-cli/0.3.1/leetcode_cli/).  Maybe this idea can be useful.

**Comment by joshcai** [comment]
Apologies for the delay - I finally found some time to work on this and have an early release available here: https://github.com/joshcai/leetcode-sync-chrome/releases/tag/v0.0.1

I will hopefully be polishing it and submitting it to the Chrome Web Store soon, but in case you wanted to try it out now (should be fully functional), you can download the .zip file and load the unpacked version in Developer Mode: https://developer.chrome.com/docs/extensions/mv2/getstarted/#manifest

**Comment by shengchen-liu** [comment]
Thank you @joshcai.  I installed your release on my Chrome browser and everything runs smoothly.
